/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayouthomeHomeRouteImport } from './routes/_layout/(home)/home'
import { Route as LayoutblogBlogRouteImport } from './routes/_layout/(blog)/blog'
import { Route as LayoutblogBlogBlogIdRouteImport } from './routes/_layout/(blog)/blog_.$blogId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayouthomeHomeRoute = LayouthomeHomeRouteImport.update({
  id: '/(home)/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutblogBlogRoute = LayoutblogBlogRouteImport.update({
  id: '/(blog)/blog',
  path: '/blog',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutblogBlogBlogIdRoute = LayoutblogBlogBlogIdRouteImport.update({
  id: '/(blog)/blog_/$blogId',
  path: '/blog/$blogId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof LayoutblogBlogRoute
  '/home': typeof LayouthomeHomeRoute
  '/blog/$blogId': typeof LayoutblogBlogBlogIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof LayoutblogBlogRoute
  '/home': typeof LayouthomeHomeRoute
  '/blog/$blogId': typeof LayoutblogBlogBlogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/(blog)/blog': typeof LayoutblogBlogRoute
  '/_layout/(home)/home': typeof LayouthomeHomeRoute
  '/_layout/(blog)/blog_/$blogId': typeof LayoutblogBlogBlogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog' | '/home' | '/blog/$blogId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/home' | '/blog/$blogId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/(blog)/blog'
    | '/_layout/(home)/home'
    | '/_layout/(blog)/blog_/$blogId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/(home)/home': {
      id: '/_layout/(home)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayouthomeHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/(blog)/blog': {
      id: '/_layout/(blog)/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LayoutblogBlogRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/(blog)/blog_/$blogId': {
      id: '/_layout/(blog)/blog_/$blogId'
      path: '/blog/$blogId'
      fullPath: '/blog/$blogId'
      preLoaderRoute: typeof LayoutblogBlogBlogIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutblogBlogRoute: typeof LayoutblogBlogRoute
  LayouthomeHomeRoute: typeof LayouthomeHomeRoute
  LayoutblogBlogBlogIdRoute: typeof LayoutblogBlogBlogIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutblogBlogRoute: LayoutblogBlogRoute,
  LayouthomeHomeRoute: LayouthomeHomeRoute,
  LayoutblogBlogBlogIdRoute: LayoutblogBlogBlogIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
